name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: ./package.sh

      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: bob-plugin
          path: ./bob-plugin-chatglm-translate-v*.bobplugin